### ISSUE TITLE
Model class Meta

### ISSUE THREAD

**Issue by tomcounsell** [tomcounsell/popoto#27]
### Model options and table metadata

In order not to pollute the model namespace, model-specific configuration is placed in a special class called Meta (a convention borrowed from the django framework)
Once the class is defined, you should not access ModelClass.Meta, but instead use ModelClass._meta
ref: [Peewee docs](https://docs.peewee-orm.com/en/latest/peewee/models.html#model-options-and-table-metadata)

Desired Features:

- [ ]  order_by to order results on query
- [ ] unique_together - use set of hashes of all existing unique keys for each class
- [ ] expires_at used to set ttl at save

Peewee Features for reference, inspiration:

```
class Meta:
    database = db
    table_name = 'model_one_tbl'
    primary_key = CompositeKey('blog', 'tag')
    indexes = ((('from_acct', 'to_acct', 'date'), True),)
    constraints = [Check('price < 10000')]
```
